//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yana4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string RentalTime { get; set; }
    }
}
